name: Varbase Starter
type: Site
description: 'A starter site template recipe for Varbase, providing a modern recipe-first approach to initializing Varbase sites.'
recipes:
  - drupal_cms_admin_ui
  - drupal_cms_anti_spam
  - drupal_cms_authentication
  - drupal_cms_blog
  - drupal_cms_forms
  - drupal_cms_media
  - drupal_cms_privacy_basic
  - drupal_cms_seo_basic
  - drupal_cms_seo_tools
  - easy_email_express
  - varbase_admin_base
install:
  - vartheme_bs5
  - project_browser
config:
  strict: false
  import:
    system:
      - system.menu.footer
  actions:
    canvas.component.block.sitemap:
      disable: []
    field.field.node.blog.field_featured_image:
      setRequired: true
    field.storage.node.field_component_tree:
      addToAllBundles:
        label: Components
        description: Stores a component tree for Canvas.
    metatag.settings:
      simpleConfigUpdate:
        entity_type_groups:
          canvas_page:
            canvas_page:
              basic: basic
    node.type.page:
      setThirdPartySettings:
        -
          module: menu_ui
          key: available_menus
          value:
            - main
            - footer
            - utility
        -
          module: menu_ui
          key: parent
          value: 'main:'
    system.site:
      simpleConfigUpdate:
        page.404: '/404'
        page.front: '/home'
    system.theme:
      simpleConfigUpdate:
        default: vartheme_bs5
    webform.webform.contact_form:
      setProperties:
        settings.confirmation_type: modal
extra:
  recipe_installer_kit:
    finish_url: '/admin/dashboard/welcome'
